#!/usr/bin/env bash

cd /home/vinicius/.dotfiles/nix/home-manager/apps/vpn/openfortivpn-webview/

sudo .

nix-shell --command zsh

appimage-run openfortivpn-webview farfetchvpn.farfetchcorp.com |
	grep SVPNCOOKIE |
	sudo openfortivpn farfetchvpn.farfetchcorp.com \
		--trusted-cert=0a8e5703f0283e9d60ed495fe78eb221eef36841ca83046acf52586d73c54b7c \
		--cookie-on-stdin &
